AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Serverless API for Mellov Application

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  DbClusterParameter:
    Type: String
    Default: 'what-appy-cluster.gsicl.mongodb.net/what'

Resources:
  # DbClusterSsmParameter:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Type: String
  #     Name: /mellov/db/cluster
  #     Value: 'some cluster'

  MellovApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: './api/mellov-api.yaml'
      # DefinitionBody:
        # 'Fn::Transform':
          # Name: 'AWS::Include'
          # Parameters:
            # Location: './api/mellov-api.yaml'

  GetSongsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetSongsFunction
      Handler: src/handlers/get-songs.getSongsHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 60
      Description: Get songs
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DB_CLUSTER: !Ref DbClusterParameter
          DB_PASSWORD: 'password'
          DB_USERNAME: 'username'
          MELLOV_CLIENT_URL: 'mellov_client'
          SPOTIFY_CLIENT_ID:  'spotify_client'
          SPOTIFY_REDIRECT_URI: 'spotify_redirect_uri'
          SPOTIFY_SECRET: 'spotify_secret'
      Events:
        GetSongsApi:
          Type: Api
          Properties:
            RestApiId: !Ref MellovApiGateway
            Path: /songs
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for prod stage"
    Value: !Sub "https://${MellovApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/"
